ffmpegYml:
    hehe: normal
    formats:
        - mp4
        - 3dostr
        - 3g2
        - 3gp
        - 4xm
        - a64
        - aa
        - aac
        - ac3
        - acm
        - act
        - adf
        - adp
        - ads
        - adts
        - adx
        - aea
        - afc
        - aiff
        - aix
        - alaw
        - alias_pix
        - amr
        - anm
        - apc
        - ape
        - apng
        - aqtitle
        - asf
        - asf_o
        - asf_stream
        - ass
        - ast
        - au
        - avfoundation
        - avi
        - avm2
        - avr
        - avs
        - bethsoftvid
        - bfi
        - bfstm
        - bin
        - bink
        - bit
        - bmp_pipe
        - bmv
        - boa
        - brender_pix
        - brstm
        - c93
        - caf
        - cavsvideo
        - cdg
        - cdxl
        - cine
        - concat
        - crc
        - dash
        - data
        - daud
        - dcstr
        - dds_pipe
        - dfa
        - dirac
        - dnxhd
        - dpx_pipe
        - dsf
        - dsicin
        - dss
        - dts
        - dtshd
        - dv
        - dvbsub
        - dvbtxt
        - dvd
        - dxa
        - ea
        - ea_cdata
        - eac3
        - epaf
        - exr_pipe
        - f32be
        - f32le
        - f4v
        - f64be
        - f64le
        - ffm
        - ffmetadata
        - fifo
        - film_cpk
        - filmstrip
        - fits
        - flac
        - flic
        - flv
        - framecrc
        - framehash
        - framemd5
        - frm
        - fsb
        - g722
        - g723_1
        - g726
        - g726le
        - g729
        - gdv
        - genh
        - gif
        - gsm
        - gxf
        - h261
        - h263
        - h264
        - hash
        - hds
        - hevc
        - hls
        - hls,applehttp
        - hnm
        - ico
        - idcin
        - idf
        - iff
        - ilbc
        - image2
        - image2pipe
        - ingenient
        - ipmovie
        - ipod
        - ircam
        - ismv
        - iss
        - iv8
        - ivf
        - ivr
        - j2k_pipe
        - jacosub
        - jpeg_pipe
        - jpegls_pipe
        - jv
        - latm
        - lavfi
        - live_flv
        - lmlm4
        - loas
        - lrc
        - lvf
        - lxf
        - m4v
        - matroska
        - matroska,webm
        - md5
        - mgsts
        - microdvd
        - mjpeg
        - mjpeg_2000
        - mkvtimestamp_v2
        - mlp
        - mlv
        - mm
        - mmf
        - mov
        - mov,mp4,m4a,3gp,3g2,mj2
        - mp2
        - mp3
        - mp4
        - mpc
        - mpc8
        - mpeg
        - mpeg1video
        - mpeg2video
        - mpegts
        - mpegtsraw
        - mpegvideo
        - mpjpeg
        - mpl2
        - mpsub
        - msf
        - msnwctcp
        - mtaf
        - mtv
        - mulaw
        - musx
        - mv
        - mvi
        - mxf
        - mxf_d10
        - mxf_opatom
        - mxg
        - nc
        - nistsphere
        - nsv
        - null
        - nut
        - nuv
        - oga
        - ogg
        - ogv
        - oma
        - opus
        - paf
        - pam_pipe
        - pbm_pipe
        - pcx_pipe
        - pgm_pipe
        - pgmyuv_pipe
        - pictor_pipe
        - pjs
        - pmp
        - png_pipe
        - ppm_pipe
        - psd_pipe
        - psp
        - psxstr
        - pva
        - pvf
        - qcp
        - qdraw_pipe
        - r3d
        - rawvideo
        - realtext
        - redspark
        - rl2
        - rm
        - roq
        - rpl
        - rsd
        - rso
        - rtp
        - rtp_mpegts
        - rtsp
        - s16be
        - s16le
        - s24be
        - s24le
        - s32be
        - s32le
        - s337m
        - s8
        - sami
        - sap
        - sbg
        - scc
        - sdp
        - sdr2
        - sds
        - sdx
        - segment
        - sgi_pipe
        - shn
        - siff
        - singlejpeg
        - sln
        - smjpeg
        - smk
        - smoothstreaming
        - smush
        - sol
        - sox
        - spdif
        - spx
        - srt
        - stl
        - stream_segment,ssegment
        - subviewer
        - subviewer1
        - sunrast_pipe
        - sup
        - svag
        - svcd
        - svg_pipe
        - swf
        - tak
        - tedcaptions
        - tee
        - thp
        - tiertexseq
        - tiff_pipe
        - tmv
        - truehd
        - tta
        - tty
        - txd
        - u16be
        - u16le
        - u24be
        - u24le
        - u32be
        - u32le
        - u8
        - uncodedframecrc
        - v210
        - v210x
        - vag
        - vc1
        - vc1test
        - vcd
        - vivo
        - vmd
        - vob
        - vobsub
        - voc
        - vpk
        - vplayer
        - vqf
        - w64
        - wav
        - wc3movie
        - webm
        - webm_chunk
        - webm_dash_manifest
        - webp
        - webp_pipe
        - webvtt
        - wsaud
        - wsd
        - wsvqa
        - wtv
        - wv
        - wve
        - xa
        - xbin
        - xmv
        - xpm_pipe
        - xvag
        - xwma
        - yop
        - yuv4mpegpipe

    codecs:
        - h264
        - 012v
        - 4xm
        - 8bps
        - a64_multi
        - a64_multi5
        - aasc
        - aic
        - alias_pix
        - amv
        - anm
        - ansi
        - apng
        - asv1
        - asv2
        - aura
        - aura2
        - av1
        - avrn
        - avrp
        - avs
        - avui
        - ayuv
        - bethsoftvid
        - bfi
        - binkvideo
        - bintext
        - bitpacked
        - bmp
        - bmv_video
        - brender_pix
        - c93
        - cavs
        - cdgraphics
        - cdxl
        - cfhd
        - cinepak
        - clearvideo
        - cljr
        - cllc
        - cmv
        - cpia
        - cscd
        - cyuv
        - daala
        - dds
        - dfa
        - dirac
        - dnxhd
        - dpx
        - dsicinvideo
        - dvvideo
        - dxa
        - dxtory
        - dxv
        - escape124
        - escape130
        - exr
        - ffv1
        - ffvhuff
        - fic
        - fits
        - flashsv
        - flashsv2
        - flic
        - flv1
        - fmvc
        - fraps
        - frwu
        - g2m
        - gdv
        - gif
        - h261
        - h263
        - h263i
        - h263p
        - h264
        - hap
        - hevc
        - hnm4video
        - hq_hqa
        - hqx
        - huffyuv
        - idcin
        - idf
        - iff_ilbm
        - indeo2
        - indeo3
        - indeo4
        - indeo5
        - interplayvideo
        - jpeg2000
        - jpegls
        - jv
        - kgv1
        - kmvc
        - lagarith
        - ljpeg
        - loco
        - m101
        - mad
        - magicyuv
        - mdec
        - mimic
        - mjpeg
        - mjpegb
        - mmvideo
        - motionpixels
        - mpeg1video
        - mpeg2video
        - mpeg4
        - mpegvideo_xvmc
        - msa1
        - mscc
        - msmpeg4v1
        - msmpeg4v2
        - msmpeg4v3
        - msrle
        - mss1
        - mss2
        - msvideo1
        - mszh
        - mts2
        - mvc1
        - mvc2
        - mxpeg
        - nuv
        - paf_video
        - pam
        - pbm
        - pcx
        - pgm
        - pgmyuv
        - pictor
        - pixlet
        - png
        - ppm
        - prores
        - psd
        - ptx
        - qdraw
        - qpeg
        - qtrle
        - r10k
        - r210
        - rawvideo
        - rl2
        - roq
        - rpza
        - rscc
        - rv10
        - rv20
        - rv30
        - rv40
        - sanm
        - scpr
        - screenpresso
        - sgi
        - sgirle
        - sheervideo
        - smackvideo
        - smc
        - smvjpeg
        - snow
        - sp5x
        - speedhq
        - srgc
        - sunrast
        - svg
        - svq1
        - svq3
        - targa
        - targa_y216
        - tdsc
        - tgq
        - tgv
        - theora
        - thp
        - tiertexseqvideo
        - tiff
        - tmv
        - tqi
        - truemotion1
        - truemotion2
        - truemotion2rt
        - tscc
        - tscc2
        - txd
        - ulti
        - utvideo
        - v210
        - v210x
        - v308
        - v408
        - v410
        - vb
        - vble
        - vc1
        - vc1image
        - vcr1
        - vixl
        - vmdvideo
        - vmnc
        - vp3
        - vp5
        - vp6
        - vp6a
        - vp6f
        - vp7
        - vp8
        - vp9
        - webp
        - wmv1
        - wmv2
        - wmv3
        - wmv3image
        - wnv1
        - wrapped_avframe
        - ws_vqa
        - xan_wc3
        - xan_wc4
        - xbin
        - xbm
        - xface
        - xpm
        - xwd
        - y41p
        - ylc
        - yop
        - yuv4
        - zerocodec
        - zlib
        - zmbv
        - 4gv
        - 8svx_exp
        - 8svx_fib
        - aac
        - aac_latm
        - ac3
        - adpcm_4xm
        - adpcm_adx
        - adpcm_afc
        - adpcm_aica
        - adpcm_ct
        - adpcm_dtk
        - adpcm_ea
        - adpcm_ea_maxis_xa
        - adpcm_ea_r1
        - adpcm_ea_r2
        - adpcm_ea_r3
        - adpcm_ea_xas
        - adpcm_g722
        - adpcm_g726
        - adpcm_g726le
        - adpcm_ima_amv
        - adpcm_ima_apc
        - adpcm_ima_dat4
        - adpcm_ima_dk3
        - adpcm_ima_dk4
        - adpcm_ima_ea_eacs
        - adpcm_ima_ea_sead
        - adpcm_ima_iss
        - adpcm_ima_oki
        - adpcm_ima_qt
        - adpcm_ima_rad
        - adpcm_ima_smjpeg
        - adpcm_ima_wav
        - adpcm_ima_ws
        - adpcm_ms
        - adpcm_mtaf
        - adpcm_psx
        - adpcm_sbpro_2
        - adpcm_sbpro_3
        - adpcm_sbpro_4
        - adpcm_swf
        - adpcm_thp
        - adpcm_thp_le
        - adpcm_vima
        - adpcm_xa
        - adpcm_yamaha
        - alac
        - amr_nb
        - amr_wb
        - ape
        - atrac1
        - atrac3
        - atrac3al
        - atrac3p
        - atrac3pal
        - avc
        - binkaudio_dct
        - binkaudio_rdft
        - bmv_audio
        - celt
        - comfortnoise
        - cook
        - dolby_e
        - dsd_lsbf
        - dsd_lsbf_planar
        - dsd_msbf
        - dsd_msbf_planar
        - dsicinaudio
        - dss_sp
        - dst
        - dts
        - dvaudio
        - eac3
        - evrc
        - flac
        - g723_1
        - g729
        - gremlin_dpcm
        - gsm
        - gsm_ms
        - iac
        - ilbc
        - imc
        - interplay_dpcm
        - interplayacm
        - mace3
        - mace6
        - metasound
        - mlp
        - mp1
        - mp2
        - mp3
        - mp3adu
        - mp3on4
        - mp4als
        - musepack7
        - musepack8
        - nellymoser
        - opus
        - paf_audio
        - pcm_alaw
        - pcm_bluray
        - pcm_dvd
        - pcm_f16le
        - pcm_f24le
        - pcm_f32be
        - pcm_f32le
        - pcm_f64be
        - pcm_f64le
        - pcm_lxf
        - pcm_mulaw
        - pcm_s16be
        - pcm_s16be_planar
        - pcm_s16le
        - pcm_s16le_planar
        - pcm_s24be
        - pcm_s24daud
        - pcm_s24le
        - pcm_s24le_planar
        - pcm_s32be
        - pcm_s32le
        - pcm_s32le_planar
        - pcm_s64be
        - pcm_s64le
        - pcm_s8
        - pcm_s8_planar
        - pcm_u16be
        - pcm_u16le
        - pcm_u24be
        - pcm_u24le
        - pcm_u32be
        - pcm_u32le
        - pcm_u8
        - pcm_zork
        - qcelp
        - qdm2
        - qdmc
        - ra_144
        - ra_288
        - ralf
        - roq_dpcm
        - s302m
        - sdx2_dpcm
        - shorten
        - sipr
        - smackaudio
        - smv
        - sol_dpcm
        - sonic
        - sonicls
        - speex
        - tak
        - truehd
        - truespeech
        - tta
        - twinvq
        - vmdaudio
        - vorbis
        - voxware
        - wavesynth
        - wavpack
        - westwood_snd1
        - wmalossless
        - wmapro
        - wmav1
        - wmav2
        - wmavoice
        - xan_dpcm
        - xma1
        - xma2
        - bin_data
        - dvd_nav_packet
        - klv
        - otf
        - scte_35
        - timed_id3
        - ttf
        - ass
        - dvb_subtitle
        - dvb_teletext
        - dvd_subtitle
        - eia_608
        - hdmv_pgs_subtitle
        - hdmv_text_subtitle
        - jacosub
        - microdvd
        - mov_text
        - mpl2
        - pjs
        - realtext
        - sami
        - srt
        - ssa
        - stl
        - subrip
        - subviewer
        - subviewer1
        - text
        - vplayer
        - webvtt
        - xsub

